#!/usr/sbin/nft -f
# fw-router nftables ruleset
# eth0 = WAN (virbr0, internet)
# eth1 = lab-net (192.168.10.0/24, all lab VMs)
# eth2 = lab-sandbox (192.168.40.0/24, isolated)

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;
        iif lo accept
        ct state established,related accept
        # allow SSH from hypervisor host (virbr0) for management
        iif eth0 ip saddr 192.168.122.0/24 tcp dport 22 accept
        iif eth1 accept
        iif eth2 ip daddr 192.168.10.10 accept
        iif eth2 drop
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
        ct state established,related accept
        iif eth1 oif eth0 accept
        iif eth0 oif eth1 ip saddr 192.168.122.0/24 accept
        iif eth2 oif eth1 ip daddr 192.168.10.10 accept
        iif eth2 drop
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }
}

table ip nat {
    chain postrouting {
        type nat hook postrouting priority 100;
        oif eth0 masquerade
    }
}
